{%set name = "py4j" %}
{%set version = "0.10.4" %}
{%set hash_type = "sha256" %}
{%set hash_val = "b49a28c6bd96d334a39c15c3ce52225585332eff5e2659c7dc7aa223aa8bd454" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - py4j
    - py4j.tests

about:
  home: http://py4j.sourceforge.net/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Enables Python programs to dynamically access arbitrary Java objects'

extra:
  recipe-maintainers:
    - pmlandwehr
