{% set name = "py4j" %}
{% set version = "0.10.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b6e5315bb3ada5cf62ac651d107bb2ebc02def3dee9d9548e3baac644ea8dbb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - py4j
    - py4j.tests
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://py4j.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Enables Python programs to dynamically access arbitrary Java objects
  dev_url: https://github.com/bartdag/py4j
  doc_url: http://py4j.sourceforge.net/

extra:
  recipe-maintainers:
    - parente
    - h-vetinari
