{% set name = "py4j" %}
{% set version = "0.10.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 624f97c363b8dd84822bc666b12fa7f7d97824632b2ff3d852cc491359ce7615

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - py4j
    - py4j.tests

about:
  home: http://py4j.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Enables Python programs to dynamically access arbitrary Java objects
  dev_url: https://github.com/bartdag/py4j
  doc_url: http://py4j.sourceforge.net/

extra:
  recipe-maintainers:
    - pmlandwehr
    - parente
