{% set name = "py4j" %}
{% set version = "0.10.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abe93d6106f5a8abbd439bcb2c50c225ea05bfb187c6a5e5a0f9120de4ad99f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - py4j
    - py4j.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://py4j.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Enables Python programs to dynamically access arbitrary Java objects
  dev_url: https://github.com/bartdag/py4j
  doc_url: http://py4j.sourceforge.net/

extra:
  recipe-maintainers:
    - parente
    - h-vetinari
